services:
  random-persister:
    container_name: random-persister
    build:
      context: .
    command: npx ts-node index.ts
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - 8083:3004
